### ISSUE TITLE
Test ICU with ofglucose unit

### ISSUE THREAD

**Issue by sffc** [icu-units/icu#126]
Try pulling in the changes from the following CLDR commit and make sure they work with ICU.

https://github.com/unicode-org/cldr/pull/951

**Comment by hugovdm** [comment]
We have a problem in unitPreferencesTest.txt. The CLDR change does the following:

- removes blood-glucose from "mass-density",
- adds blood-glucose to "concentration",
- adds a unitAlias, replacing "milligram-per-deciliter" with "milligram-ofglucose-per-deciliter".

In unitPreferencesTest.txt, we still have:

```
mass-density;	blood-glucose;	001;	11 / 1000;	0.011;	kilogram-per-cubic-meter;	11 / 10;	1.1;	milligram-per-deciliter
mass-density;	blood-glucose;	001;	1 / 100;	0.01;	kilogram-per-cubic-meter;	1;	1.0;	milligram-per-deciliter
mass-density;	blood-glucose;	001;	9 / 1000;	0.009;	kilogram-per-cubic-meter;	9 / 10;	0.9;	milligram-per-deciliter
```

Consequently:
- This test no longer succeeds, due to removal of blood-glucose use case from unitPreferences: the result is given in kilogram-per-cubic-meter instead.
- This probably needs to be replaced by a concentration test instead of a mass-density test.

**Comment by hugovdm** [comment]
That's not all. For unit preferences, we recognise "kilogram-per-cubic-meter" as a mass-density measurement - we can't recognise that there's a concentration preference for it - we don't automatically recognise it can be converted to a concentration via use of "ofglucose".

**Comment by sffc** [comment]
CC @macchiati @pedberg-icu

**Comment by hugovdm** [comment]
CLDR ticket dealing with the ofglucose pseudo-unit: https://unicode-org.atlassian.net/browse/CLDR-13654

**Comment by macchiati** [comment]
Note that https://unicode-org.atlassian.net/browse/CLDR-14232 is the one
making the fix.

Mark

**Comment by hugovdm** [comment]
FYI: unitPreferencesTest.txt was also fixed in CLDR (thanks Mark!) - I had just previously grabbed CLDR before that PR was merged.
