### ISSUE TITLE
Figure out correct flow for isPercent/isPermille

### ISSUE THREAD

**Issue by hugovdm** [icu-units/icu#149]
Consider isCldrUnit in number_formatimpl.cpp:

    bool isCldrUnit = !isCurrency
        && !isBaseUnit
        && (unitWidth == UNUM_UNIT_WIDTH_FULL_NAME
            || !(isPercent || isPermille)
            || isCompactNotation
        );

When `unitWidth != FULL_NAME && (isPercent || isPermille) && !isCompactNotation`, we're not using LongNameHandler. This means sometimes when we format percent or permille, gender does not show up in FormattedNumber.getGender().

**Comment by hugovdm** [comment]
For isPercent and isPermille the code is using a different patternStyle:

            patternStyle = CLDR_PATTERN_STYLE_PERCENT;

With this pattern style, formatting is done with the "percentFormat" formatting pattern instead of considering it to be "formatting a unit" - so "unit/concentr/percent" information is never accessed, and gender is not loaded.

Taking a look at `de` data, the "percentFormat" pattern looks like this:

                percentFormat{"#,##0 %"}

The "unit*/concentr/percent" patterns look like this:

            percent{
                dnam{"%"}
                one{"{0} %"}
                other{"{0} %"}
            }
            permille{
                one{"{0} ‰"}
                other{"{0} ‰"}
            }

I conclude from the pattern that percentFormat does do things that normal unit formatting patterns don't do.

**Comment by younies** [comment]
@sffc , type out the reasoning and close

**Comment by sffc** [comment]
The short percent/permille format is its own standalone format that has been in ICU for a very long time.  It is different than the long form percent/permille, which runs through the full units code path.  We should not change how we handle short form percent/permille.

@macchiati also pointed out that since the unit with plain percent formatting never changes, translators writing message strings can assume that it always has the same gender.
