### ISSUE TITLE
Test what happens when you give a negative number

### ISSUE THREAD

**Issue by sffc** [icu-units/icu#63]
ICU shouldn't crash.  It's okay if it returns an error code.  If it returns a real result, the result should make sense.

**Comment by hugovdm** [comment]
State at the head of the "1 foot 12 inches" branch (since that fixes some "complex conversion" issues): mixed units fail to format correctly. Fortunately, other units format fine.
Java and C++ have different failure modes, due to different implementations.

The test cases I added can be seen in the branch for this PR: https://github.com/hugovdm/icu/pull/5

C++:

            FAIL: Negative numbers: time: Unsafe Path; got "-2 Std., 0 Min. und 0 Sek."; expected "-1 Std., 14 Min. und 24 Sek."
            FAIL: Negative numbers: minute-and-second: Skeleton Path: 'measure-unit/duration-second usage/media': -77.700000000000003; got "-78 sec"; expected "-1 min, 18 sec"

Java:

    : Negative numbers: time: Unsafe Path: -1.24: expected "-1 Std., 14 Min. und 24 Sek.", got "-2 Std., 45 Min. und 36 Sek."
    : Negative numbers: minute-and-second: Unsafe Path: -77.7: expected "-1 min, 18 sec", got "-78 sec"

Attention needed for both geq handling and complex conversion.

**Comment by hugovdm** [comment]
I'm thinking maybe go ahead and implement "make the first number negative, take the absolute values for the rest", taking it as most probably correct for most locales (if not all).
